### ISSUE TITLE
IndexError on get_word

### ISSUE THREAD

**Issue by lajanki** [lajanki/steam-game-descriptor#10]
In rare cases choosing a successor can fail on empty sets. If the training data ends with a previously unseen word, that word will end  up without successors to choose from.

```
Traceback (most recent call last):
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/venv/lib/python3.10/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/venv/lib/python3.10/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/main.py", line 35, in generate_game_description
    description = generator()
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/src/generate_description.py", line 151, in __call__
    "value": self.generators.system_requirements.sound_card.generate(
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/src/generator/generator.py", line 61, in generate
    word = self.get_word()
  File "/home/xxx/projects/gae_websites/steam-game-descriptor/src/generator/generator.py", line 95, in get_word
    next_word = random.choice(list(self.model[self._key]))
  File "/usr/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

**Comment by lajanki** [comment]
The root cause is probably not a unique trailing word in the training data as the last ngram extracted consists of `n-1` word prefix and `1` word successor; every ngram should have at least one successor.

Nevertheless, error handling on such cases has been deopyed.
